### ISSUE TITLE
lsp-copilot package seems to freeze sublime text 4

### ISSUE THREAD

**Issue by solrevdev** [TheSecEng/LSP-copilot#51] opened 2022-08-16 10:00 UTC
I have LSP and various others installed and working. 

I installed LSP-Copilot and restarted as per the docs but then no Copilot: command pallete items appear and then a few seconds later it freezes forcing me to force quit. 

When I restart it freezes again. I managed to get some screenshots before I force quit 

![](https://i.imgur.com/5Yq9bXY.jpg)

![](https://i.imgur.com/tDNzvSE.jpg)

![](https://i.imgur.com/cGiPrQz.jpg)

System info:
```text
neofetch --off
solrevdev@macmini-office.local
------------------------------
OS: macOS 11.6.8 20G730 x86_64
Host: Macmini7,1
Kernel: 20.6.0
Uptime: 1 hour, 34 mins
Packages: 329 (brew)
Shell: zsh 5.8
Resolution: 2560x1440
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: CaskaydiaCoveNerdFontComplete-Regular 16
CPU: Intel i5-4278U (4) @ 2.60GHz
GPU: Intel Iris
Memory: 9494MiB / 16384MiB
```

**Comment by jfcherng** [comment] 2022-08-16 10:09
Could you take a screenshot (or copy) for ST console? Maybe there are some error messages.

**Comment by solrevdev** [comment] 2022-08-16 10:18
> Could you take a screenshot (or copy text) for ST console? Maybe there are some error messages.

I'll try killing the process and restarting and see if I can get the console up before it freezes. In meantime here is my activity monitor while it beach ball freezes...

![](https://i.imgur.com/DLqtnVc.jpg)

Thanks for looking at this for me by the way I'm so excited to get copilot working with sublime!

**Comment by solrevdev** [comment] 2022-08-16 10:36
Ok I managed to get here before the freeze. Now any movement is just beach ball!

![](https://i.imgur.com/cF9q0lJ.jpg)

I will leave it open and update here in case more gets written to the console at any point

**Comment by jfcherng** [comment] 2022-08-16 12:05
From my experiment, it doesn't play well with Node v18. As a workaround, you can create `Packages/User/lsp_utils.sublime-settings` with the following settings to use portable Node v16 for LSP-* plugins.

```js
{
    // Specifies the type and priority of the Node.js installation that should be used for Node.js-based servers.
    // The allowed values are:
    //  - 'system' - a Node.js runtime found on the PATH
    //  - 'local' - a Node.js runtime managed by LSP that doesn't affect the system
    // The order in which the values are specified determines which one is tried first,
    // with the later one being used as a fallback.
    // You can also specify just a single value to disable the fallback.
    "nodejs_runtime": [
        // "system",
        "local",
    ],
}
```

**Comment by jfcherng** [comment] 2022-08-16 12:14
I classify this as won't fix since the server is compiled as WASM files in https://github.com/github/copilot.vim/tree/release/copilot/dist and there is no way to fix on our side, most likely.

**Comment by jfcherng** [comment] 2022-08-16 12:16
Okay, so the latest server release obviously mark Node v18 as unsupported.
https://github.com/github/copilot.vim/commit/554460008f18cbffecb9f1e5de58fec8410dc16f

**Closed by jfcherng** 2022-08-16 12:16 UTC
Labels: wontfix

**Comment by solrevdev** [comment] 2022-08-16 12:18
YES! 

Thank you so much for your help its very much appreciated. 

I now have copilot working in sublime text.

**Comment by hakusaro** [comment] 2022-09-15 05:26
I suggest pinning this issue (I ended up here from #58) because I nearly made another dupe of it.

**Comment by mherrmann** [comment] 2022-11-02 08:07
A note to people who don't have _Copilot: Sign In_ in the Command Palette: There seem to be a few caveats.

Firstly, for me, any _Copilot_ commands only show up in the Command Palette if I have a file open. So make sure to have an open file in front of you. It's strange that this also seems to be the case for the "Sign In" command. It shouldn't require a file.

Secondly, if you already signed into Copilot from another IDE, then you will also not see _Sign In_. At least, that's how it was for me. I signed into Copilot via JetBrains PyCharm. It seems that the plugin in Sublime Text picks this up and doesn't show _Sign In_ in that case. I do have _Sign Out_ and others, despite never logging into Copilot in ST.

**Comment by jfcherng** [comment] 2022-11-02 09:26
> Firstly, for me, any _Copilot_ commands only show up in the Command Palette if I have a file open. So make sure to have an open file in front of you. It's strange that this also seems to be the case for the "Sign In" command. It shouldn't require a file.

yes, the command only shows if LSP-copilot is activated on the current view...

> Secondly, if you already signed into Copilot from another IDE, then you will also not see Sign In. At least, that's how it was for me. I signed into Copilot via JetBrains PyCharm. It seems that the plugin in Sublime Text picks this up and doesn't show Sign In in that case. I do have Sign Out and others, despite never logging into Copilot in ST.

Interesting, didn't know this.

**Comment by TerminalFi** [comment] 2022-11-02 11:44
Signin is due to the fact that copilot saves its signin info in your ~/ location for all editors.
